import Image from "next/image";
import { cn } from "@/lib/utils";

/**
 * Byte & Brain logo — the circuit "B" mark (themed raster) + wordmark set in
 * type. The full provided lockup has a small, vertically-centered wordmark that
 * becomes illegible in a compact header, so we pair the mark with real text we
 * can size precisely. Mark files are generated by `npm run prepare-logo`.
 * next/image gives us explicit dimensions (no CLS) + optimized delivery.
 */
export function Logo({ className }: { className?: string }) {
  return (
    <span className={cn("inline-flex items-center gap-2.5", className)}>
      <Image
        src="/brand/logo-mark-light.png"
        alt=""
        width={385}
        height={317}
        loading="eager"
        className="h-8 w-auto shrink-0 dark:hidden"
      />
      <Image
        src="/brand/logo-mark-dark.png"
        alt=""
        width={383}
        height={316}
        loading="eager"
        className="hidden h-8 w-auto shrink-0 dark:block"
      />
      <span className="text-[15px] font-bold uppercase leading-none tracking-[0.06em]">
        <span className="text-foreground">Byte</span>
        <span className="text-muted-foreground"> &amp; </span>
        <span className="text-gradient-brand">Brain</span>
      </span>
    </span>
  );
}

/** The full provided lockup (mark + wordmark + tagline) — for large brand moments. */
export function LogoLockup({ className }: { className?: string }) {
  return (
    <span className={cn("inline-block", className)}>
      <Image
        src="/brand/logo-light.png"
        alt="Byte & Brain"
        width={1491}
        height={329}
        className="h-auto w-full dark:hidden"
      />
      <Image
        src="/brand/logo-dark.png"
        alt="Byte & Brain"
        width={1486}
        height={328}
        className="hidden h-auto w-full dark:block"
      />
    </span>
  );
}
